# Generated by Django 2.1 on 2018-08-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=25)),
                ('url', models.URLField()),
                ('suggested_link_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mpaa_rating', models.CharField(max_length=5)),
                ('critics_pick', models.IntegerField()),
                ('headline', models.CharField(max_length=255)),
                ('summary_report', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('opening_date', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('date_created_local', models.DateTimeField(auto_now_add=True)),
                ('date_modified_local', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimedia_type', models.CharField(max_length=25)),
                ('src', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('movie_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.MovieReview')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='movie_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.MovieReview'),
        ),
    ]
